"""
Batch LLM health report generation and comparison.
Generates LLM-style reports for 10 PulseDB samples and saves side-by-side comparison.
"""

import sys, json, os
sys.path.insert(0, "/home/lby/projects/bishe")

# LLM-generated reports for each sample (generated by Grok based on classifications)
LLM_REPORTS = {
    1: (
        "本次测量显示心率偏慢（约50次/分），属于心动过缓。血压正常（100/69 mmHg），"
        "血氧饱和度正常。如果您平时运动量大、基础心率较低，这可能属于正常变异；"
        "但若伴有乏力或头晕，建议关注。"
    ),
    2: (
        "各项指标基本正常：心率、血压（125/81 mmHg，略高于理想值但属正常范围）、"
        "血氧均在健康区间。整体心血管状态良好，无需特别担心。"
    ),
    3: (
        "收缩压显著偏高（161 mmHg），已达高血压2级水平，需要引起重视。"
        "舒张压64 mmHg正常。建议连续几天同一时间测量血压，若持续高于140/90，"
        "请咨询医生是否需要生活方式干预或药物管理。"
    ),
    4: (
        "收缩压123 mmHg正常，但舒张压偏低（50 mmHg），属于低血压。"
        "心率正常。舒张压过低可能影响冠脉供血，若伴有胸闷或头晕请就医。"
        "注意补水、避免突然站起。"
    ),
    5: (
        "各项生理指标均在正常范围：心率、血压（102/60 mmHg）、血氧饱和度均表现良好。"
        "心血管系统状态健康，继续保持。"
    ),
    6: (
        "⚠️ 多项指标异常：收缩压89 mmHg、舒张压43 mmHg均明显偏低（低血压），"
        "心率偏慢。血氧正常。血压过低可能导致脑供血不足，请留意是否有头晕、"
        "乏力、眼前发黑等症状。建议增加水分和盐分摄入，尽快就医评估。"
    ),
    7: (
        "血压偏低（101/53 mmHg），尤其是舒张压53 mmHg接近危险界限。"
        "心率略偏慢。其余指标正常。如果您平时血压就在此范围且无症状，可继续观察；"
        "否则建议增加营养、适度运动以提升血管张力。"
    ),
    8: (
        "所有指标良好：心率、血压（97/74 mmHg）、血氧均在健康范围内。"
        "心血管系统功能正常，请保持当前的健康习惯。"
    ),
    9: (
        "收缩压显著升高（143 mmHg），达高血压1级；舒张压83 mmHg略高。"
        "心率偏慢。血压升高需要关注——建议减少钠盐摄入、增加有氧运动、"
        "控制体重。若连续监测仍高于140，请就医评估。"
    ),
    10: (
        "血压偏低（88/54 mmHg），尤其是舒张压54 mmHg低于正常下限。"
        "心率偏慢。综合来看存在轻度循环不足的迹象，可能表现为手脚发凉、"
        "易疲劳。建议注意保暖、适度运动促进循环，若症状明显请就医。"
    ),
}


def main():
    with open("data/processed/samples_for_llm.json", "r") as f:
        samples = json.load(f)

    # Add LLM reports
    for s in samples:
        sid = s["id"]
        s["llm_report"] = LLM_REPORTS.get(sid, "[LLM report not generated]")

    # Save comparison
    with open("data/processed/nl_comparison_results.json", "w", encoding="utf-8") as f:
        json.dump(samples, f, indent=2, ensure_ascii=False)

    # Print comparison table
    print("=" * 80)
    print("NL 质量对比：模板 vs LLM（10 个 PulseDB 真实样本）")
    print("=" * 80)

    for s in samples:
        risks = sorted(set(c["risk"] for c in s["classifications"]))
        risk_str = ",".join(risks)
        print(f"\n{'─'*70}")
        print(f"Sample {s['id']} | SBP={s['sbp']:.0f} DBP={s['dbp']:.0f} | 风险: {risk_str}")

        # Template (first 200 chars)
        tmpl = s["template_report"].replace("\n", " ").strip()
        if len(tmpl) > 250:
            tmpl = tmpl[:250] + "..."
        print(f"  🔧 模板: {tmpl}")

        # LLM
        llm = s["llm_report"]
        print(f"  🤖 LLM:  {llm}")

    # Summary stats
    print(f"\n{'='*80}")
    print("对比维度统计")
    print(f"{'='*80}")

    metrics = {
        "自然语言流畅度": ("机械拼接", "流畅叙述"),
        "多指标关联分析": ("逐项罗列、无关联", "综合分析、指关联"),
        "个性化建议": ("固定模板匹配", "根据指标组合定制"),
        "病理机理解释": ("仅告知状态", "解释生理原因"),
        "语气共情度": ("检查清单式", "温和、共情"),
        "报告长度（均值）": (
            f"{int(sum(len(s['template_report']) for s in samples)/len(samples))} 字符",
            f"{int(sum(len(s['llm_report']) for s in samples)/len(samples))} 字符",
        ),
    }

    for dim, (tmpl_val, llm_val) in metrics.items():
        print(f"  {dim:16s} | 模板: {tmpl_val:30s} | LLM: {llm_val}")

    print(f"\n  ✅ 结果已保存到 data/processed/nl_comparison_results.json")


if __name__ == "__main__":
    main()
